package org.openhab.binding.xbmc.rpc.api.model.list.filter.fields;

public enum Movies {
	title, 
    plot, 
    plotoutline, 
    tagline, 
    votes, 
    rating, 
    time, 
    writers, 
    playcount, 
    lastplayed, 
    inprogress, 
    genre, 
    country, 
    year, 
    director, 
    actor, 
    mpaarating, 
    top250, 
    studio, 
    hastrailer, 
    filename, 
    path, 
    set, 
    tag, 
    dateadded, 
    videoresolution, 
    audiochannels, 
    videocodec, 
    audiocodec, 
    audiolanguage, 
    subtitlelanguage, 
    videoaspect, 
    playlist
}
